### ISSUE TITLE
How to merge different XML reports to get cumulative report?

### ISSUE THREAD

**Issue by tomkoptel** [Kotlin/kotlinx-kover#425]
Hello team 👋

First of all, thank you for the great effort put into the project 🙇

# Environment

- Android Gradle Plugin 7.4.2
- Kover 0.7.2
- Junit 4.13.2
- Java 11.0.18
- Kotlin 1.8.22

# The Question

`How to merge 3 different XML reports produced by 3 different test runs into one so that I can get aggregated coverage report?`

Each group of tests produces different coverage numbers for the same class of sources.
In my case, the unit tests produce 21%, snapshot 7%, and headless-ui 50% coverage.
Executing all tests without filtering produces 62% coverage.

I need to get 62% coverage in the end. I have 3 instances of app/build/reports/kover/report.xml generated per test run.

It is important to note that the respective test groups executed separately on GitHub actions as dedicated jobs.
I can not execute all tests simultaneously to get the aggregated coverage report, as I need to parallelize test groups execution.

# Setup

In the project, I have 3 annotations HeadlessUITests, SnapshotTests, and UITests.
In every test class under src/main/test/kotlin I have a test method annotated with one of the above
annotations.

```kotlin
import org.junit.experimental.categories.Category
import my.junit.categories.SnapshotTests

@Category(SnapshotTests::class)
class AvatarViewSnapshotTest
```

The aforementioned annotations used in conjunction with `org.gradle.api.tasks.testing.Test`
and `org.gradle.api.tasks.testing.junit.JUnitOptions` API.
So that I can execute different group of tests relying on project gradle properties.

For example execute:

```shell
./gradlew :app:koverLog :app:koverHtmlReport :app:koverXmlReport -PonlyTests=unit
```

# The Project Setup

```groovy
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kover'
    id 'my.junit.categories'
}

koverReport {
    filters {
        excludes {
            // excludes class by fully-qualified JVM class name, wildcards '*' and '?' are available
            classes(
                    "*.BuildConfig",
                    "*.*_Factory*",
                    "*.di.*",
                    "*.*MembersInjector*",
                    "*.*_HiltModules*",
                    "*.Hilt_*",
                    "hilt_aggregated_deps.*",
                    "dagger.hilt.internal.aggregatedroot.codegen.*",
                    "*.*previewProviders.*",
                    "*.*previews.*",
                    "*.*IdlingResource*",
                    "*.*ExtensionsKt*",
                    "*.extensions.*",
                    "*.databinding.*"
            )
            // excludes all classes located in specified package and it subpackages, wildcards '*' and '?' are available
            packages("hilt_aggregated_deps")
            // excludes all classes and functions, annotated by specified annotations, wildcards '*' and '?' are available
            annotatedBy("*Generated*")
        }
    }
}

koverReport {
    defaults {
        // adds the contents of the reports of `debug` Android build variant to default reports
        mergeWith("debug")
    }
}

dependencies {
    kover(project(":some-java-lib"))
    kover(project(":some-android-lib"))
}
```

# The `my.junit.categories`

```kotlin
import com.android.build.gradle.AppExtension
import com.android.build.gradle.LibraryExtension
import com.android.build.gradle.internal.dsl.TestOptions
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.testing.Test
import org.gradle.api.tasks.testing.junit.JUnitOptions
import org.gradle.kotlin.dsl.the
import org.gradle.kotlin.dsl.withType

open class JunitCategoriesPlugin : Plugin<Project> {

    private companion object {
        const val ANNOTATION_GROUP = "my.junit.categories"
        const val FAST = "$ANNOTATION_GROUP.UnitTests"
        const val SNAPSHOT = "$ANNOTATION_GROUP.SnapshotTests"
        const val HEADLESS_UI = "$ANNOTATION_GROUP.HeadlessUITests"
        val CATEGORIES = setOf(FAST, SNAPSHOT, HEADLESS_UI)
    }

    override fun apply(project: Project) = project.run {
        plugins.withId("java") {
            tasks.withType<Test> { project.configureTestFilters(this) }
        }
        plugins.withId("com.android.library") {
            the<LibraryExtension>().run {
                testOptions.connectJunitCategories(project)
            }
        }
        plugins.withId("com.android.application") {
            the<AppExtension>().run {
                testOptions.connectJunitCategories(project)
            }
        }
    }

    private fun TestOptions.connectJunitCategories(project: Project) {
        unitTests.all { test -> project.configureTestFilters(test) }
    }

    private fun Project.configureTestFilters(test: Test) {
        val onlyMode = !(project.properties["onlyTests"] as? String).isNullOrBlank()
        if (onlyMode) {
            selectCategory(onlyMode)?.let { onlyOneCategory(it) }
        }
    }

    private fun selectCategory(mode: String?): String? = when (mode) {
        "unit" -> FAST
        "snapshot" -> SNAPSHOT
        "headless-ui" -> HEADLESS_UI
        else -> null
    }

    private fun JUnitOptions.onlyOneCategory(category: String) {
        includeCategories = CATEGORIES.intersect(setOf(category))
        excludeCategories = CATEGORIES.subtract(setOf(category))
    }
}
```

**Comment by shanshin** [comment]
Hi,
could you clarify, there is no way to run tests for different categories in parallel within the same build run? Each category is tested only in its own GitHub action, by a separate Gradle launch?

**Comment by tomkoptel** [comment]
Hello @shanshin , thank you for a quick response :) 

I have 3 jobs executed in isolation from each other in separate runners. Then I store the XML report and pass one to codecov to merge those for me. I am looking for a way to avoid using codecov and merge 3 reports with a means of `kover`.

Here is the simplified config file for steps and a screenshot of the setup. I hope it does clarify your question :) 

```yml
jobs:
  unit-tests:
    steps:
        - name: Execute Unit Tests
          shell: bash
          run: |
            ./gradlew :app:koverLog :app:koverHtmlReport :app:koverXmlReport -PonlyTests=unit --stacktrace
        - name: Save XML report
          uses: actions/upload-artifact@v3
          with:
            name: unit-coverage-xml
            path: |
              app/build/reports/kover/*.xml
        - name: Zip HTML report
          uses: montudor/action-zip@v1
          with:
            args: zip -qq -r unit-html-report.zip app/build/reports/kover/html
        - name: Save HTML report
          uses: actions/upload-artifact@v3
          with:
            name: unit-coverage-html
            path: |
              unit-html-report.zip
   snapshot-tests:
        # check out repo as above
        - name: Execute Unit Tests
          shell: bash
          run: |
            ./gradlew :app:koverLog :app:koverHtmlReport :app:koverXmlReport -PonlyTests=snapshot --stacktrace
        # upload artifacts as above
   headless-ui-tests:
        # check out repo as above
        - name: Execute Unit Tests
          shell: bash
          run: |
            ./gradlew :app:koverLog :app:koverHtmlReport :app:koverXmlReport -PonlyTests=headless-ui --stacktrace
        # upload artifacts as above
    upload_codecov:
      steps:
        - name: Download Unit Tests Coverage
          uses: actions/download-artifact@v3
          with:
            name: unit-coverage-xml
            path: unit-coverage-xml
        - name: Upload Unit Tests
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: unittests
            files: unit-coverage-xml/report.xml
        - name: Download Snapshot Tests Coverage
          uses: actions/download-artifact@v3
          with:
            name: snapshot-coverage-xml
            path: snapshot-coverage-xml
        - name: Upload Snapshot Tests
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: snapshottests
            files: snapshot-coverage-xml/report.xml
        - name: Download Headless UI Tests Coverage
          uses: actions/download-artifact@v3
          with:
            name: headless-ui-coverage-xml
            path: headless-ui-coverage-xml
        - name: Upload Headless UI Tests
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: headlessuitests
            files: headless-ui-coverage-xml/report.xml
```

<img width="850" alt="Screenshot 2023-07-10 at 23 17 09" src="https://github.com/Kotlin/kotlinx-kover/assets/758909/5569ce23-1a26-451b-b8c3-245940ab16d8">
